### ISSUE TITLE
请问 dict.txt 是通过什么语料得到的呢？

### ISSUE THREAD

**Issue by Anastasia-Zhang** [sunyilgdx/SIFRank_zh#14]

**Comment by sunyilgdx** [comment]
jieba分词自带的词典，pip install jieba以后，可以在python\Lib\site-packages\jieba目录下找到，这里主要使用了它的词频统计信息，也可以通过大规模的语料自行统计

**Comment by Anastasia-Zhang** [comment]
好的 谢谢！
