### ISSUE TITLE
代码运行没报错，但是没有输出结果，是什么原因呢

### ISSUE THREAD

**Issue by Listen1007** [sunyilgdx/SIFRank_zh#15]
![8](https://user-images.githubusercontent.com/29428026/111281371-d48a5d80-8677-11eb-84f7-a306179c8eda.png)

**Comment by sunyilgdx** [comment]
看一下是不是这里没改 #2

**Comment by Listen1007** [comment]
> 看一下是不是这里没改 #2

![image](https://user-images.githubusercontent.com/29428026/111437521-2a293d80-873e-11eb-8cd1-9dd93bb5a5e5.png)
请问是改这个路径下的elmo.py吗？不知道我是否改对了？

**Comment by sunyilgdx** [comment]
应该是对的 @Listen1007
