### ISSUE TITLE
模型下载失败

### ISSUE THREAD

**Issue by songsh** [sunyilgdx/SIFRank_zh#20]
下载zhs, thulac 都失败，有其它地方下吗？

**Comment by sunyilgdx** [comment]
刚试了，可以正常下载 @songsh

**Comment by songsh** [comment]
能把下载url 贴出来吗？

**Comment by sunyilgdx** [comment]
不是已经贴出来了吗，再Readme里面 @songsh

**Comment by songsh** [comment]
zhs.model 没下来，http://39.96.43.154/zhs.model.tar.bz2  是这个url 吗，下不了？

**Comment by sunyilgdx** [comment]
这不是点一下就开始下载了吗？ @songsh

**Comment by songsh** [comment]
很奇怪，不能点击下，要拷出来，才会下。我再试下

**Comment by sunyilgdx** [comment]
我一点就下载了，用的是Edge浏览器
