### ISSUE TITLE
批量处理句子

### ISSUE THREAD

**Issue by clouddesert** [sunyilgdx/SIFRank_zh#28]
首先感谢分享您的工作.
请问是否实现有批量处理句子的接口, 即用类似batch的方式而不是单个句子进行提交.
期待答复

**Comment by 1sebsgithub1** [comment]
你好，请问您现在解决了吗

**Comment by sunyilgdx** [comment]
> 你好，请问您现在解决了吗

由于在处理单个句子的时候用到了句子分割和批次处理，所以没有做多句子的方式

**Comment by yml-blog** [comment]
用问相关的
