### ISSUE TITLE
可否上线一个简单的网页 demo？

### ISSUE THREAD

**Issue by wqcabjkcuh** [sunyilgdx/SIFRank_zh#3]
利于展示模型的性能，也方便直观感受模型的优点

**Comment by sunyilgdx** [comment]
您的想法确实很好，但是由于设备和时间的原因，实在是没办法实现。近期（两周左右）我准备上传一个同样环境（分词、标注等都采用StanfordCoreNLP包）的关键词抽取代码集合，是基于[pke](https://github.com/boudinfl/pke)这个仓库改写的，可以在本地运行实验一下效果，或者验证数据集。
