### ISSUE TITLE
匹配时报错

### ISSUE THREAD

**Issue by ScottishFold007** [sunyilgdx/SIFRank_zh#7]
哈喽，大神，我又来了，这次是这个报错：
![image](https://user-images.githubusercontent.com/36957508/82136679-b5962180-9842-11ea-81ee-bd98ab353e50.png)

**Comment by sunyilgdx** [comment]
可以再给多一点信息吗？比如说测试的样例，现在有些定位不到错误在哪

**Comment by ScottishFold007** [comment]
> 可以再给多一点信息吗？比如说测试的样例，现在有些定位不到错误在哪

我观察过，只要去掉字符串里的换行符就可以了，'xxxxxxxxxxxx'.replace('\n','')
