### ISSUE TITLE
清华分词工具包THULAC thulac.models,应该下载哪个model?

### ISSUE THREAD

**Issue by Yazooliu** [sunyilgdx/SIFRank_zh#8]
我无法确定下载链接里面应该下载哪一个model?

**Comment by sunyilgdx** [comment]
[应该是这个地址](http://thulac.thunlp.org/sendMessage_v1_1) 要填一下个人信息
Models_v1_v2.zip   THULAC模型，包括分词模型和词性标注模型（适用于lite版）   58.2MB 2016-01-10 [download](http://thulac.thunlp.org/source/Models_v1_v2.zip)
然后解压到自己的目录下

**Comment by meisa233** [comment]
我申请了pro版，在自己的数据集上表现更好一些，但是是否真的提升了性能需要以后做更详细的测试。

**Comment by zdaiot** [comment]
@meisa233 请问您测试的时候采用什么指标啊？

**Comment by meisa233** [comment]
> @meisa233 请问您测试的时候采用什么指标啊？

不好意思，我做的这个项目已经过去许久了，我当时应该是用来提取关键词了，提取关键词的准确度还是挺高的（提取关键词符合主题的个数与提取的关键词的个数之比）
